/**
 * Memory Architecture Interfaces
 *
 * MemGPT-inspired 5-tier memory system:
 *   Working → Episodic → Semantic → Procedural → Archival
 *
 * Each tier has different latency, capacity, and retrieval characteristics.
 * The MemoryArchitect orchestrates retrieval cascades across tiers.
 */

// ─── Core Memory Entry ────────────────────────────────────────

export interface MemoryEntry {
  id: string
  content: string
  metadata: MemoryMetadata
  embedding?: Float32Array
  createdAt: number
  updatedAt: number
  accessCount: number
  lastAccessedAt: number
  importance: number          // 0-1, computed by ImportanceScorer
  decayFactor: number         // Current decay multiplier (Ebbinghaus curve)
}

export interface MemoryMetadata {
  source: MemorySource
  tier: MemoryTier
  agentId?: string            // Which agent created this memory
  sessionId?: string          // Which session it belongs to
  projectId?: string          // Project context
  tags: string[]
  associations: string[]      // IDs of related memories
  contentType: 'text' | 'code' | 'workflow' | 'fact' | 'preference' | 'summary'
  confidence: number          // 0-1, how reliable is this memory
  pinned: boolean             // Exempt from decay/compaction
}

export type MemoryTier = 'working' | 'episodic' | 'semantic' | 'procedural' | 'archival'

export type MemorySource =
  | 'user_input'              // Directly stated by user
  | 'agent_output'            // Generated by an agent
  | 'extraction'              // Extracted from conversation by LLM
  | 'compaction'              // Result of compacting older memories
  | 'workflow_learning'       // Learned from repeated patterns
  | 'import'                  // Imported from external source

// ─── Tier-Specific Types ──────────────────────────────────────

/** Working Memory: Always in context, < 4K tokens */
export interface WorkingMemoryState {
  currentTask: string | null
  recentMessages: WorkingMessage[]
  activeAgentId: string | null
  scratchpad: Record<string, unknown>  // Agent can store intermediate state
  tokenCount: number
  maxTokens: number                     // Default 4096
}

export interface WorkingMessage {
  role: 'user' | 'assistant' | 'system'
  content: string
  timestamp: number
  agentId?: string
  tokenEstimate: number
}

/** Episodic Memory: Session-based experiences with temporal ordering */
export interface EpisodicEntry extends MemoryEntry {
  sessionId: string
  sequenceIndex: number       // Position within the session
  emotionalValence: number    // -1 (negative) to +1 (positive) — user sentiment
  outcome: 'success' | 'failure' | 'partial' | 'unknown'
  relatedTaskId?: string
}

/** Procedural Memory: Learned workflows and patterns */
export interface ProceduralEntry extends MemoryEntry {
  trigger: string             // Natural language trigger condition
  steps: ProceduralStep[]
  successRate: number         // 0-1, based on outcome tracking
  executionCount: number
  lastExecutedAt: number
  requiredCapabilities: string[]
}

export interface ProceduralStep {
  order: number
  action: string              // Description of what to do
  agentRole?: string          // Which agent type should do this
  toolName?: string           // Specific tool to use
  expectedOutput?: string     // What a successful output looks like
}

/** Archival Memory: Compressed long-term storage */
export interface ArchivalEntry extends MemoryEntry {
  originalEntryCount: number  // How many memories were compacted into this
  originalTier: MemoryTier    // What tier they came from
  dateRange: { start: number; end: number }
  compressionRatio: number    // tokens_original / tokens_compressed
}

// ─── Search & Retrieval ───────────────────────────────────────

export interface MemoryQuery {
  text: string                // Natural language query
  tiers?: MemoryTier[]        // Which tiers to search (default: all)
  limit?: number              // Max results per tier
  minRelevance?: number       // Minimum similarity score (0-1)
  agentId?: string            // Filter by agent
  sessionId?: string          // Filter by session
  projectId?: string          // Filter by project
  tags?: string[]             // Filter by tags
  contentType?: MemoryMetadata['contentType']
  timeRange?: { start: number; end: number }
  includeDecayed?: boolean    // Include memories below decay threshold
}

export interface MemorySearchResult {
  entry: MemoryEntry
  relevance: number           // 0-1, combined score
  matchType: 'semantic' | 'keyword' | 'temporal' | 'associative'
  tier: MemoryTier
  explanation?: string        // Why this memory was relevant
}

export interface MemoryCascadeResult {
  results: MemorySearchResult[]
  tiersSearched: MemoryTier[]
  totalSearchTimeMs: number
  tokenBudgetUsed: number
  tokenBudgetTotal: number
}

// ─── Memory Tier Interface ────────────────────────────────────

export interface MemoryTierProvider {
  readonly tier: MemoryTier
  readonly name: string

  /** Initialize the tier (create tables, etc.) */
  init(): Promise<void>

  /** Add a memory to this tier */
  add(entry: MemoryEntry): Promise<string>

  /** Update an existing memory */
  update(id: string, updates: Partial<MemoryEntry>): Promise<void>

  /** Remove a memory from this tier */
  remove(id: string): Promise<void>

  /** Search this tier */
  search(query: MemoryQuery): Promise<MemorySearchResult[]>

  /** Get a single memory by ID */
  get(id: string): Promise<MemoryEntry | null>

  /** Get all memories in this tier (with pagination) */
  list(offset: number, limit: number): Promise<MemoryEntry[]>

  /** Count memories in this tier */
  count(): Promise<number>

  /** Estimate token usage of this tier */
  estimateTokens(): Promise<number>

  /** Get memories eligible for promotion to a higher tier */
  getPromotionCandidates(limit: number): Promise<MemoryEntry[]>

  /** Get memories eligible for demotion to a lower tier */
  getDemotionCandidates(limit: number): Promise<MemoryEntry[]>
}

// ─── Compaction & Lifecycle ───────────────────────────────────

export interface CompactionConfig {
  /** How often to run compaction (ms) */
  intervalMs: number

  /** Max memories per tier before triggering compaction */
  tierLimits: Record<MemoryTier, number>

  /** Minimum importance score to keep (below this, compact or discard) */
  importanceThreshold: number

  /** Days of inactivity before a memory is eligible for demotion */
  demotionDaysInactive: number

  /** Ebbinghaus forgetting curve half-life in days */
  decayHalfLifeDays: number

  /** If true, pinned memories are never compacted */
  respectPins: boolean
}

export interface CompactionResult {
  memoriesCompacted: number
  memoriesPromoted: number
  memoriesDemoted: number
  memoriesDiscarded: number
  tokensFreed: number
  durationMs: number
}

// ─── Importance Scoring ───────────────────────────────────────

export interface ImportanceFactors {
  recency: number             // How recently accessed (0-1)
  frequency: number           // How often accessed (0-1)
  relevance: number           // Semantic similarity to current context (0-1)
  explicitImportance: number  // User/agent marked importance (0-1)
  sourceReliability: number   // How reliable the source (0-1)
  uniqueness: number          // How different from other memories (0-1)
}

export interface ImportanceWeights {
  recency: number
  frequency: number
  relevance: number
  explicitImportance: number
  sourceReliability: number
  uniqueness: number
}

// ─── Memory Events ────────────────────────────────────────────

export type MemoryEvent =
  | { type: 'memory:added'; tier: MemoryTier; entryId: string }
  | { type: 'memory:updated'; tier: MemoryTier; entryId: string }
  | { type: 'memory:removed'; tier: MemoryTier; entryId: string }
  | { type: 'memory:promoted'; entryId: string; fromTier: MemoryTier; toTier: MemoryTier }
  | { type: 'memory:demoted'; entryId: string; fromTier: MemoryTier; toTier: MemoryTier }
  | { type: 'memory:compacted'; result: CompactionResult }
  | { type: 'memory:cascade_search'; query: string; tiersSearched: MemoryTier[]; resultsFound: number }

// ─── Defaults ─────────────────────────────────────────────────

export const DEFAULT_COMPACTION_CONFIG: CompactionConfig = {
  intervalMs: 5 * 60 * 1000,         // Every 5 minutes
  tierLimits: {
    working: 50,                       // ~4K tokens
    episodic: 500,                     // Recent sessions
    semantic: 5000,                    // Core knowledge
    procedural: 200,                   // Learned workflows
    archival: 50000,                   // Compressed history
  },
  importanceThreshold: 0.15,
  demotionDaysInactive: 14,
  decayHalfLifeDays: 30,
  respectPins: true,
}

export const DEFAULT_IMPORTANCE_WEIGHTS: ImportanceWeights = {
  recency: 0.25,
  frequency: 0.20,
  relevance: 0.25,
  explicitImportance: 0.15,
  sourceReliability: 0.10,
  uniqueness: 0.05,
}
