/**
 * Provider Abstraction Layer — Phase 1.1 of the Nyra 5-Year Plan
 *
 * Defines universal interfaces for LLM, embedding, and vision providers.
 * Any provider (OpenAI, Anthropic, Gemini, Ollama, NPU, future) implements these.
 *
 * This is the core contract that all LLM providers must satisfy.
 */

// ============================================================================
// MULTIMODAL CONTENT BLOCKS
// ============================================================================

/**
 * A text content block.
 */
export interface TextContentBlock {
  type: 'text'
  text: string
}

/**
 * An image content block (base64-encoded).
 */
export interface ImageContentBlock {
  type: 'image'
  source: {
    type: 'base64'
    media_type: 'image/png' | 'image/jpeg' | 'image/gif' | 'image/webp'
    data: string  // base64-encoded image data (no data URI prefix)
  }
}

/**
 * A tool_use content block returned by the model (Anthropic format).
 */
export interface ToolUseContentBlock {
  type: 'tool_use'
  id: string
  name: string
  input: Record<string, unknown>
}

/**
 * A tool_result content block sent back to the model (Anthropic format).
 */
export interface ToolResultContentBlock {
  type: 'tool_result'
  tool_use_id: string
  content: string
}

/**
 * Union of all content block types.
 */
export type ContentBlock =
  | TextContentBlock
  | ImageContentBlock
  | ToolUseContentBlock
  | ToolResultContentBlock

/**
 * Content field: either a plain string (backward-compat) or an array of content blocks.
 */
export type MessageContent = string | ContentBlock[]

// ============================================================================
// CHAT INTERFACES
// ============================================================================

/**
 * A single message in a conversation.
 */
export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: MessageContent
  name?: string           // For tool calls, the tool name
  toolCallId?: string     // For tool responses, the tool call ID
}

/**
 * Anthropic computer_use tool definition.
 * This is a special tool type for the computer-use beta.
 */
export interface ComputerUseTool {
  type: 'computer_20241022'
  name: 'computer'
  display_width_px: number
  display_height_px: number
}

/**
 * Request to the LLM for chat completion.
 */
export interface ChatRequest {
  messages: ChatMessage[]
  model?: string          // Override model for this request
  maxTokens?: number
  temperature?: number
  topP?: number
  stop?: string[]
  stream?: boolean
  tools?: ToolDefinition[]
  computerUseTools?: ComputerUseTool[]  // Anthropic computer_use beta tools
  responseFormat?: 'text' | 'json'
  betaHeaders?: string[]                // e.g. ['computer-use-2024-10-22']
}

/**
 * Complete response from chat completion.
 */
export interface ChatResponse {
  content: string
  model: string
  provider: string
  usage: TokenUsage
  finishReason: 'stop' | 'length' | 'tool_calls' | 'error'
  toolCalls?: ToolCall[]
  latencyMs: number
}

/**
 * Streamed chunk from chat completion.
 */
export interface ChatChunk {
  content: string
  done: boolean
  model?: string
  usage?: TokenUsage
}

/**
 * Token usage statistics.
 */
export interface TokenUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
}

// ============================================================================
// TOOL INTERFACES
// ============================================================================

/**
 * Specification for a tool the LLM can call.
 */
export interface ToolDefinition {
  name: string
  description: string
  parameters: Record<string, unknown>  // JSON Schema
}

/**
 * A tool call generated by the LLM.
 */
export interface ToolCall {
  id: string
  name: string
  arguments: string  // JSON string
}

// ============================================================================
// EMBEDDING INTERFACES
// ============================================================================

/**
 * Request for text embeddings.
 */
export interface EmbeddingRequest {
  texts: string[]
  model?: string
}

/**
 * Response containing embeddings.
 */
export interface EmbeddingResponse {
  embeddings: Float32Array[]
  model: string
  dimensions: number
  usage: { totalTokens: number }
}

// ============================================================================
// HEALTH & DISCOVERY
// ============================================================================

/**
 * Health status of a provider.
 */
export interface ProviderHealth {
  status: 'healthy' | 'degraded' | 'down'
  latencyMs: number
  lastCheckedAt: number
  error?: string
}

/**
 * Capabilities of a specific model.
 */
export interface ModelCapabilities {
  supportsVision: boolean
  supportsTools: boolean
  supportsStreaming: boolean
  supportsJson: boolean
  contextWindow: number
  maxOutputTokens: number
}

/**
 * Model metadata for discovery and selection.
 */
export interface ModelCard {
  id: string
  name: string
  provider: string
  capabilities: ModelCapabilities
  costPer1kInput?: number    // USD
  costPer1kOutput?: number   // USD
}

// ============================================================================
// CORE PROVIDER INTERFACE
// ============================================================================

/**
 * Main provider interface — all LLM providers implement this.
 *
 * Examples: OpenAI, Anthropic, Ollama, Gemini, Copilot, OpenRouter
 */
export interface LLMProvider {
  readonly id: string
  readonly name: string
  readonly isLocal: boolean     // true for Ollama, NPU; false for cloud

  // ── Lifecycle ──
  initialize(): Promise<void>
  shutdown(): Promise<void>

  // ── Health ──
  healthCheck(): Promise<ProviderHealth>
  isAvailable(): boolean

  // ── Models ──
  listModels(): Promise<ModelCard[]>
  getModelCapabilities(modelId: string): ModelCapabilities | null

  // ── Chat ──
  chat(request: ChatRequest): Promise<ChatResponse>
  chatStream(request: ChatRequest): AsyncGenerator<ChatChunk>

  // ── Embeddings (optional) ──
  supportsEmbeddings(): boolean
  embed?(request: EmbeddingRequest): Promise<EmbeddingResponse>
}

// ============================================================================
// PROVIDER FACTORY & CONFIGURATION
// ============================================================================

/**
 * Factory for creating provider instances.
 */
export interface LLMProviderFactory {
  id: string
  name: string
  create(config: ProviderConfig): LLMProvider
}

/**
 * Configuration passed to provider factories.
 */
export interface ProviderConfig {
  apiKey?: string
  baseUrl?: string
  organizationId?: string
  timeout?: number
  maxRetries?: number
  customHeaders?: Record<string, string>
}

// ============================================================================
// PROVIDER ERRORS
// ============================================================================

/**
 * Typed error for provider-specific failures.
 */
export class ProviderError extends Error {
  constructor(
    public readonly providerId: string,
    public readonly code: string,
    message: string,
    public readonly statusCode?: number,
    public readonly retryable?: boolean,
  ) {
    super(`[${providerId}] ${code}: ${message}`)
    this.name = 'ProviderError'
  }
}
